const jwt = require('./jwt');
const assert = require('chai').assert;
const { JWT_PAYLOAD } = require('../../test/utils');

// // // //

// Stores the token generated by jwt.sign(...)
let token = '';

// Stores the verified payload pulled from the signed token
const verify_payload = {
  id: 0,
  username: ''
};

// // // //

describe('/lib/jwt.js', () => {
  describe('sign valid token', () => {
  it('verify signed JWT should equal original payload', () => {
    // Signs the payload
    token = jwt.sign(JWT_PAYLOAD);

    // Verifies the payload
    let verify_payload = jwt.verify(token);

    // Asserts equality of original payload and signed/verified payload
    assert.equal(JWT_PAYLOAD.id, verify_payload.id);
    assert.equal(JWT_PAYLOAD.username, verify_payload.username);
  });
  });
});
